### ISSUE TITLE
Why is CSRF protection explicit by default?

### ISSUE THREAD

**Issue by erdlet** [jakartaee/mvc#22]
Since a while I ask myself, why the specification defines explicit CSRF protection as a default instead of the implicit one. 

From a security point of view, IMO every web application should use CSRF protection by default, because nobody wants an per default enabled attack point. I think, the specification should help users to build secure web applications and let them think about what they are doing, in case they really want to disable this security feature.

Would be great to get an explanation for this design decision :)

**Comment by ivargrimstad** [comment]
It was discussed on the mailing list back in 2016. The default was then OFF, but we changed it to EXPLICIT. I don't think we really discussed setting IMPLICIT as the default. Probably because we want to let the developer have finer-grained control bu default by using the `@CsrfValid` annotation. Maybe @chkal has better memory :)

**Comment by erdlet** [comment]
> Probably because we want to let the developer have finer-grained control bu default by using the @CsrfValid annotation

Thanks for this info. In case this was the intention, I understand it, but I'm afraid that many people don't think about security, because other MVC frameworks like Rails or Spring Security (especially in combination with Thymeleaf) take care of that automatically. In these frameworks, I need to disable this security feature manually, so I'm really aware of what I'm doing. To have a weaker default setting could lead to a lot of insecure applications, which are hard to secure afterwards.

**Comment by chkal** [comment]
It's been a while, but AFAIK @ivargrimstad is correct. The initial default was `OFF` and I proposed to change it to `EXPLICIT` because users were confused that adding the annotation to controllers didn't have any effect (see https://github.com/mvc-spec/mvc-spec/commit/7a5cab9).

However, I agree that `IMPLICIT` may have been a better choice. I'm not sure if we can change this as part of the next major release. Maybe this would be acceptable?

**Comment by erdlet** [comment]
I think the next major release would be a good point for that. Because we already have breaking changes through the namespace switch, I think we can expect the users to adapt this too. Also, I guess that there will be more complex productive MVC applications after the next major release and an addition of the API to the Jakarta EE umbrella, which would make an later adaption more painful.

**Comment by chkal** [comment]
Agreed! Let's target this for 2.0

**Comment by erdlet** [comment]
I talked to Christian a few days ago because I saw that we forgot this in MVC 2.0. We think that we shall target this for 3.0 somewhere in the future.

@ivargrimstad Is it OK to create a milestone for 3.0 and add this issue, even it is far in the future, so we can't forget it again?

**Comment by ivargrimstad** [comment]
> I talked to Christian a few days ago because I saw that we forgot this in MVC 2.0. We think that we shall target this for 3.0 somewhere in the future.
> 
> @ivargrimstad Is it OK to create a milestone for 3.0 and add this issue, even it is far in the future, so we can't forget it again?

Yes, go ahead!
